### ISSUE TITLE
Lulu and Georgia

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#100]
- [x] 846  https://www.stedi.com/app/guides/import/01H3ZW0QCM542Q46V96K52NEF3
- [x] 850  https://www.stedi.com/app/guides/import/01H3ZW8HPF321BMEBK27BHB1X4
- [x] 855  https://www.stedi.com/app/guides/import/01H3ZFTS65K5Z5N1XEMR73Q105
- [x] 856  https://www.stedi.com/app/guides/import/01H3ZVK71HG4XMW2ZCBG6T437C

**Comment by gennadykim** [comment]
done
