### ISSUE TITLE
RXO

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#101]
- [x] 204  https://www.stedi.com/app/guides/import/01H41VYMRAHRQ127H6DTPAT2F2
- [x] 214  https://www.stedi.com/app/guides/import/01H41W84CA4DHRQK5FSE09G2FE
- [x] 990  https://www.stedi.com/app/guides/import/01H41WB9E1QP6VTK8TQ22WBAY0

**Comment by gennadykim** [comment]
done
