### ISSUE TITLE
CDW

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#16]
- [x] 810
- [x] 832
- [x] 846
- [x] 850
- [x] 855
- [x] 856
- [x] 867
- [x] 870

**Comment by AlexJamesEDI** [comment]
CDW 855 Purchase Order Acknowledgement Completed
Import Link - https://www.stedi.com/app/guides/import/01H5Q8BN7637JCQA3MTNYZSKQZ

**Comment by AlexJamesEDI** [comment]
Picking up 856 next

**Comment by AlexJamesEDI** [comment]
Import Link for 810 - https://www.stedi.com/app/guides/import/01H6DP276TWT8P51Y9324CJZW3

**Comment by AlexJamesEDI** [comment]
Import Link for 846 - https://www.stedi.com/app/guides/import/01H6NFNKK0K069T16MP170R0T9

**Comment by AlexJamesEDI** [comment]
CDW 832 Price Sales Catalog Completed.
Import Link for 832 - https://www.stedi.com/app/guides/import/01H6TTQENERTM5MGKFW8TV69VW
**Point to Note:** BCT03 in the CDW PDF is NOT correct. The Element Name and ID indicates it is BCT09. I have created BCT09 instead of BCT03 in the Stedi Guide.

**Comment by AlexJamesEDI** [comment]
CDW 867 Product Transfer and Resale Report Completed
Import Link for 867 - https://www.stedi.com/app/guides/import/01H72B6S852TYXEJSMK4MTC61Q
**Points to Note:**
PTD01 - Usage is missing in the guide. As part of the base x12, this is set to Mandatory. Have set PTD01 as mandatory.
LIN Segment element numbering is NOT proper. I have updated the Stedi guide to have LIN13 and LIN14 as well.

**Comment by AlexJamesEDI** [comment]
CDW 870 Order Status Report Completed
Import Link for 870 - https://www.stedi.com/app/guides/import/01H72MSY08PY10PX5TV07CYPBC
**Points to Note**
ISR01 has Code HQ repeated thrice.Usually unique codes are assigned for different purposes, but the same HQ code is assigned for different purposes. I have clubbed all the purposes for the same HQ code.
![image_360](https://github.com/Stedi-Demos/edi-guide-catalog/assets/139342127/c431d57c-2f7f-4166-86b0-ab2d0d2ac739)
![image_720](https://github.com/Stedi-Demos/edi-guide-catalog/assets/139342127/9e7be5db-ff83-41da-b259-b0f051bddf67)
