### ISSUE TITLE
CSA Software

### ISSUE THREAD

**Issue by dkanter14** [Stedi-Demos/edi-guide-catalog#168]
- [x] 211  https://www.stedi.com/app/guides/import/01H7EB9CCR8P7NZTYFW5JZM2KD

[WT_X12_4010_211OBtoVend_20230501.pdf](https://github.com/Stedi-Demos/edi-guide-catalog/files/12307056/WT_X12_4010_211OBtoVend_20230501.pdf)

**Comment by gennadykim** [comment]
- they changed the standard G63-03 qualifiers L and E
- actually they often use their own description for the codes. For example G62-01 of 68 means "Requested Delivery Date" but they changed it to just "Delivery Date"
- sample is incorrect, I changed it

**Comment by gennadykim** [comment]
done
