### ISSUE TITLE
GameStop

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#37]
- [x] 810  https://www.stedi.com/app/guides/import/01H81R3D79CCW4J2DJ9GSG1GTT
- [x] 850  https://www.stedi.com/app/guides/import/01H81SNH1H2W8EHXGJ4Y9BPYMR
- [x] 855  https://www.stedi.com/app/guides/import/01H82A1Y2S5ZD3JT12FSEBF52C
- [x] 856  https://www.stedi.com/app/guides/import/01H82BDX0KJ622ZPA4VHS7G680

**Comment by gennadykim** [comment]
done

**Comment by gennadykim** [comment]
@nickwein done
