### ISSUE TITLE
Hamburg Sud

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#41]
- [x] 214  https://www.stedi.com/app/guides/import/01H3NENT922TRKG1SXE0J517JS
- [x] 300  https://www.stedi.com/app/guides/import/01H3NG54CAQDWBS1H4XWVR1EH6
- [x] 301  https://www.stedi.com/app/guides/import/01H3NHRGT4F5NJY0XYT9DCJ1YX
- [x] 310 bill of landing  https://www.stedi.com/app/guides/import/01H3SSQMC8TB26FPA29QCWDFYM
- [x] 310 invoice  https://www.stedi.com/app/guides/import/01H47M4J8ZQA12Q3QJSZJVKWKZ
- [x] 315  https://www.stedi.com/app/guides/import/01H41ZQ2WP1DA3DAKA3GKS7JAD
- [x] 322  https://www.stedi.com/app/guides/import/01H42137HAXW6QYT7YX6AD7MPJ

**Comment by gennadykim** [comment]
had to remove P0304 rule from AT7 because multiple samples didn't follow it

**Comment by gennadykim** [comment]
done
