### ISSUE TITLE
JCrew

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#47]
- [x] 850  https://www.stedi.com/app/guides/import/01H4BF3YVEPYQMJ5DP4Y3JJJCK
- [x] 855  https://www.stedi.com/app/guides/import/01H4BFHK7DNXNSGKXJ80PV630R
- [x] 856  https://www.stedi.com/app/guides/import/01H4BH1EQHXN2VKJNHWMX787YY
- [x] 860  https://www.stedi.com/app/guides/import/01H4ENXNQCR3V9N3A8TV4TG1VN

**Comment by gennadykim** [comment]
856 - they want PO4 under HL (P) and HL (T) to be repeatable (so vendor can provide both gross and net weights) but I cannot make it repeatable in Guides

**Comment by gennadykim** [comment]
done
