### ISSUE TITLE
AT&T

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#5]
- [x] 811 [Published guide](https://www.stedi.com/app/guides/view/at-t/consolidated-service-invoicestatement/01H0QC9QB55MACB8HRF89HJRVK)
- [x] 810  https://www.stedi.com/app/guides/import/01H2HDHGNTNTABKHC3A02H4YHW
- [x] 824  https://www.stedi.com/app/guides/import/01H2JZBE471M7WFRZN9FGB0QRF
- [x] 846  https://www.stedi.com/app/guides/import/01H2JZX0WBYCXYZ5EEQ7TB4SQE
- [x] 850  https://www.stedi.com/app/guides/import/01H2M7WN4W49BPRBM1G9V6FYVQ
- [x] 855  https://www.stedi.com/app/guides/import/01H2N96VYK3GQ6HSXDQKVW02PV
- [x] 856  https://www.stedi.com/app/guides/import/01H2NG3CN91S0NYT48YGGTX74Z
- [x] 860  https://www.stedi.com/app/guides/import/01H2PP4550ZD5K520EB53X2JXQ
- [x] 867  https://www.stedi.com/app/guides/import/01H2M4DM8XJHH5STCSZ57CYPY6
- [x] 997  https://www.stedi.com/app/guides/import/01H2PPC9MGE48NDVWQVSNRW049

**Comment by kasiafojucik** [comment]
drop a link to a guide xyz

**Comment by gennadykim** [comment]
856 is huge, there are multiple HL levels (S O T P I K) and multiple combinations are possible

SOTPIK
SOTIK
SOPIK
SOIK

took time

**Comment by gennadykim** [comment]
done
