### ISSUE TITLE
O'Reilly

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#57]
- [x] 810  https://www.stedi.com/app/guides/import/01H3X1JW34RWBG96368AK5B666
- [x] 846  https://www.stedi.com/app/guides/import/01H3X23G0GMGYBY7ZZZ4XYWNEA
- [x] 850  https://www.stedi.com/app/guides/import/01H3X05PPYGV455JHY6QY75BE9
- [x] 856  https://www.stedi.com/app/guides/import/01H3WZE384RF0WZEVQ7VYH80F8
- [x] 865  https://www.stedi.com/app/guides/import/01H3WZP2J89B5KF5FR26S95437

**Comment by gennadykim** [comment]
856 - they do not use HL-02 so I had to add it manually to the sample data to make it working

**Comment by gennadykim** [comment]
865 - bad quality specs, probably created manually

overall the data samples are not good

**Comment by gennadykim** [comment]
done
