### ISSUE TITLE
OmniLogistics

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#60]
- [x] 210  https://www.stedi.com/app/guides/import/01H7BFMEM6MX3RJ12TGSYPEKGY
- [x] 214  https://www.stedi.com/app/guides/import/01H7BGSR58KJDG0843C6A4FEE4

[Omni X12 210 - 4010 (2) (1).pdf](https://github.com/Stedi-Demos/edi-guide-catalog/files/12294917/Omni.X12.210.-.4010.2.1.pdf)

[Omni X12 214 - 4010 (2) (1).pdf](https://github.com/Stedi-Demos/edi-guide-catalog/files/12294918/Omni.X12.214.-.4010.2.1.pdf)

**Comment by nickwein** [comment]
@gennadykim @jeevankumar-g @AlexJamesEDI These guides are a priority for a customer. Can one of you please assign yourself to this build?

**Comment by gennadykim** [comment]
I'll take care of these

**Comment by nickwein** [comment]
Great - moving to In Progress.

**Comment by gennadykim** [comment]
about 210, there are the following issues

- G62-03 (time qualifier) is marked as mandatory while there is no G62-04 (time) so P0304 wouldn't work. No G62-03 in the sample and no values - so I didn't add this element
- segment samples are generated, make no sense (I added them but they are useless)
- L1-03 has the list of qualifiers of L and K, which do not belong to the standard, plus this element is ID 2/2. In the sample they used FR (flat rate) so I decided to leave it empty (there is no L or K in the standard; not clear which other qualifiers apart from FR might be used)

**Comment by gennadykim** [comment]
about 214

- no codes in N1-01, N1-05, N1-06 and N4-05 - these elements are IDs and it doesn't make much sense to have them w/o qualifiers
- segment samples are generated and do not make much sense

**Comment by gennadykim** [comment]
@nickwein  done
