### ISSUE TITLE
Saks Fifth Avenue

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#62]
- [x] 810 - CANADA ONLY - https://www.stedi.com/app/guides/import/01H410J67N7A01MMJ07ZND9ZHN
- [x] 810 - US ONLY - https://www.stedi.com/app/guides/import/01H411NWNRAWQBGB3JHWXSKMZ1
- [x] 820 - https://www.stedi.com/app/guides/import/01H41JEGJP0XCANVP7Y5AKZHR6
- [x] 824 - https://www.stedi.com/app/guides/import/01H41K20THZ9NXS4X6ERTG0NGM
- [x] 850 - https://www.stedi.com/app/guides/import/01H41NGYDHKDWB8HW0QVCSRZF1
- [x] 852 - https://www.stedi.com/app/guides/import/01H41NX4QZPJKJDXJ4SBG4AZWF
- [x] 855 - https://www.stedi.com/app/guides/import/01H42WXQT68KMC5DQFNYN572FW
- [x] 856 - https://www.stedi.com/app/guides/import/01H42XNEP7GQMZ5E9SJ09NFVBD

**Comment by jeevankumar-g** [comment]
There was no clear instruction on the optional elements/loops, all have been set as mandatory.
Ready for review.
