### ISSUE TITLE
Shop Rite (Dropship)

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#64]
Dropship

- [x] 810  https://www.stedi.com/app/guides/import/01H3GBTCBHHE3322T9Y54QDJ1M
- [x] 846  https://www.stedi.com/app/guides/import/01H3GC6HVVD6G6077PTZQZJ8VF
- [x] 850  https://www.stedi.com/app/guides/import/01H3GCQ4Y19F5DGQ1JWYEW1BDP
- [x] 855  https://www.stedi.com/app/guides/import/01H3GCWX7Y3DZ064ZZP950AJJ4
- [x] 856  https://www.stedi.com/app/guides/import/01H3B7EPH4DMXZVRVSP49J6XQR
- [x] 864  https://www.stedi.com/app/guides/import/01H3GD37E5WWMNDZJK5VW8QQPF

**Comment by gennadykim** [comment]
done
