### ISSUE TITLE
Staples

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#67]
- [x] 810  https://www.stedi.com/app/guides/import/01H3QWBEXWFFEMPFXP0QEXVK58
- [x] 812  https://www.stedi.com/app/guides/import/01H3R7KZ9DZJ93M4HQ7YFZ01H0
- [x] 816  https://www.stedi.com/app/guides/import/01H3R78Q5DCWVMQGPF77KY00AQ
- [x] 820  https://www.stedi.com/app/guides/import/01H3R7YQ89AEX47RC55MGCCX3B
- [x] 824  https://www.stedi.com/app/guides/import/01H3R7C6JNX6KCY7KPM8MVTN37
- [x] 850  https://www.stedi.com/app/guides/import/01H3QW1CVGY8QDPK2Y9PNRQ3EW
- [x] 852  https://www.stedi.com/app/guides/import/01H3QWHAH1PVJD0EY6VYC1534X
- [x] 856  https://www.stedi.com/app/guides/import/01H3QXHRDSQZYB38HFPH50FEHV
- [x] 860  https://www.stedi.com/app/guides/import/01H3R7VPHPDRN9FQSERG6G91S0

**Comment by gennadykim** [comment]
there are two 856s - Standard Pack (SOIP) and Pick and Pack (SOPI), I created one spec for both

**Comment by gennadykim** [comment]
done
