### ISSUE TITLE
Summit Racing

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#70]
- [x] 810
- [x] 846
- [x] 850
- [x] 856

**Comment by dkanter14** [comment]
@nickwein i believe Summit Racing is already live, want to close this out? https://www.stedi.com/app/guides/view/summit-racing/purchase-order/01H2X17CZYVGZ6SXVNV3QB9CMQ/import

**Comment by nickwein** [comment]
@dkanter14 done
