### ISSUE TITLE
Target

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#71]
- [x] 810 - https://www.stedi.com/app/guides/import/01H2RG0K3Z081YP9QZC7A804FN
- [x] 820 - https://www.stedi.com/app/guides/import/01H2SVBQ2HHAP58X0312FEZA6E
- [x] 850 - https://www.stedi.com/app/guides/import/01H2WDD2TTV41151HWF2QGX706
- [x] 856 - https://www.stedi.com/app/guides/import/01H2X6F3163VG6QF66K2RG9NTC
- [x] 860 - https://www.stedi.com/app/guides/import/01H2WMVAJJMVJSCS7CG0B4HVR6

**Comment by gennadykim** [comment]
some text

**Comment by jeevankumar-g** [comment]
Ready for Review

**Comment by kasiafojucik** [comment]
thanks!
