### ISSUE TITLE
Walgreens

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#83]
Stocking:

- [x] 810 - https://www.stedi.com/app/guides/import/01H301ZW329VDQ6VDZ02EJMV90
- [x] 850 - https://www.stedi.com/app/guides/import/01H31NTNM3X376FFWM94F2G4BD
- [x] 850 - Domestic - https://www.stedi.com/app/guides/import/01H31Y446AW3QF9R1NP7QFPF8X
- [x] 856 - https://www.stedi.com/app/guides/import/01H325TMJ8PND2MTJ7SYSRPBAQ
- [x] 860 - https://www.stedi.com/app/guides/import/01H32BS2W66NTBBZ9QP9C4QX95
- [x] 860 Domestic - https://www.stedi.com/app/guides/import/01H32D36FVH52AZFY7K3GAE3EH
- [x] 861 - https://www.stedi.com/app/guides/import/01H303EQ8NZ5HS6B50MYC9B2KY

Direct Store Delivery:

- [x] 180 - https://www.stedi.com/app/guides/import/01H39M50JJ3V0J0XFG624N700R
- [x] 810 - https://www.stedi.com/app/guides/import/01H39K1W7JG9F0J2VX6B8PW82R
- [x] 820 - https://www.stedi.com/app/guides/import/01H39WH5H7PTDH5YZ1E2PCMQQF
- [x] 850 - https://www.stedi.com/app/guides/import/01H3A671XTSV1T8F4H2B3QWS4X
- [x] 856 - https://www.stedi.com/app/guides/import/01H3GVNCMVGKBTA44XNFYDT0VW
- [x] 861 - https://www.stedi.com/app/guides/import/01H3A2PNT3CB63D3VETP50BMX9

**Comment by jeevankumar-g** [comment]
Ready for review
