### ISSUE TITLE
XPO

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#86]
- [ ] 204  <<< the spec is incorrect, it is just an entire standard
- [x] 210
- [x] 214  https://www.stedi.com/app/guides/import/01H2TKW0CKJN88W5B9ST1XGSFH

**Comment by gennadykim** [comment]
204 is not correct - it is an entire standard with all segments, elements and qualifiers

**Comment by kasiafojucik** [comment]
got it, skip if that's the case

**Comment by gennadykim** [comment]
done
