### ISSUE TITLE
Walmart

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#91]
- [x] 850
- [x] 856
- [x] 163  https://www.stedi.com/app/guides/import/01H2H980NYB3HJ5M811MSGH3J9
- [x] 212  https://www.stedi.com/app/guides/import/01H2HAX4ZX5YEGKSB1J0T46S95
- [x] 824  https://www.stedi.com/app/guides/import/01H2HBVVJDHFG7B8JVMPZH6VEH

**Comment by gennadykim** [comment]
done
