### ISSUE TITLE
GCommerce Super Spec

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#93]
https://www.gcommerceinc.com/resources/super-spec/

- [x] 850  https://www.stedi.com/app/guides/import/01H3TDSB3JDBD87T8P2990C037
- [x] 810  https://www.stedi.com/app/guides/import/01H3TD8XWBFY285MP5WBV68267
- [x] 856  https://www.stedi.com/app/guides/import/01H3TEY0QXS0Q3D19R4VDG49AH
- [x] 997  https://www.stedi.com/app/guides/import/01H3TF9PS66GJYWQWBZKR63KQW

**Comment by gennadykim** [comment]
done
