### ISSUE TITLE
VendorNet

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#94]
- [x] 810  https://www.stedi.com/app/guides/import/01H30MJHJ6S1AVBE9AAD3E6EE2
- [x] 846  https://www.stedi.com/app/guides/import/01H30KMD4W9W7VF0RRJ1R9H0SA
- [x] 850  https://www.stedi.com/app/guides/import/01H30M2J8ETX2886X8D4EZZT4J
- [x] 856  https://www.stedi.com/app/guides/import/01H30MBR2WYDNHEER7AHG3WDB0

**Comment by gennadykim** [comment]
started working on these. No version, looks like 4010 (dates, references, the specs are from 2005)

**Comment by gennadykim** [comment]
done
