### ISSUE TITLE
HubEDI Walmart

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#95]
- [x] 850 -https://www.stedi.com/app/guides/import/01H3Y5FFPE3VTKGV6WT2QFR84Y
- [x] 855 - https://www.stedi.com/app/guides/import/01H3SVZVJBX809T8MR1HYM345T
- [x] 846 - https://www.stedi.com/app/guides/import/01H3Y2NFWVEXMRB3M9HVDC7FN8
- [x] 856 - https://www.stedi.com/app/guides/import/01H3Z0EHT8NKXBP5260HQGD9HD
- [x] 860 - https://www.stedi.com/app/guides/import/01H3STYZT3VR8972SQ4T89MXTX
- [x] 997 - https://www.stedi.com/app/guides/import/01H3STA1FETQG769N6PE7PRB1Y

**Comment by jeevankumar-g** [comment]
Done - Ready for review
