### ISSUE TITLE
exWorks

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#96]
- [x] 204  https://www.stedi.com/app/guides/import/01H3BA1AYX6PKEF2CMPREZXNAX
- [x] 210  https://www.stedi.com/app/guides/import/01H3BA8K5MT1FSY33CTMJ4X807
- [x] 214  https://www.stedi.com/app/guides/import/01H3B8XD43JWWHAV1BKDN1NQP0

**Comment by gennadykim** [comment]
214 is very bad quality spec. They want to use loop 210 - it is CD3, but there is no CD3 definition in the spec. So I added it with all the fields optional. Plus not standard L11 qualifier (FN), plus they marked mandatory elements as optional

**Comment by gennadykim** [comment]
done
