### ISSUE TITLE
Tractor Supply DTC

### ISSUE THREAD

**Issue by kasiafojucik** [Stedi-Demos/edi-guide-catalog#98]
- [x] 180  https://www.stedi.com/app/guides/import/01H3F6M22M6WT6VPE6RPKE39NE
- [x] 810  https://www.stedi.com/app/guides/import/01H3FME93216GY04DC3SNXBRRT
- [x] 846  https://www.stedi.com/app/guides/import/01H3FMQB5J04V15YXNZVWGWCW3
- [x] 850  https://www.stedi.com/app/guides/import/01H3FKYASFRY1YY3K5Y34MGJ1P
- [x] 855  https://www.stedi.com/app/guides/import/01H3FMYPJ96ND17RP6WS50ETJ4
- [x] 856  https://www.stedi.com/app/guides/import/01H3FNDAPF5Y7ME4BHNT4QZ5VT
- [x] 860  https://www.stedi.com/app/guides/import/01H3FNK1ZQN3A13ASMQK928GW3
- [x] 870  https://www.stedi.com/app/guides/import/01H3FNVHPH0F9VDDA72ZZKZM19

**Comment by gennadykim** [comment]
there is 850 among the PDFs, do we need it as well ?

**Comment by gennadykim** [comment]
added 850 per discussison

**Comment by gennadykim** [comment]
there is a small issue with 850 - SCAC code should be UPSN, not USPN for United Parcel Service

**Comment by gennadykim** [comment]
done
